### ISSUE TITLE
How to parse an optional token?

### ISSUE THREAD

**Issue by ccorcos** [sighingnow/parsec.py#11]
suppose I have optional arguments: `Approve()` or `Approve(a, b)`. How would I specify that the arguments are optional?

**Comment by ccorcos** [comment]
I'm hoping theres something we can do like `p.maybe(moreArgs)` which returns none and backtracks if theres nothing...

**Comment by ccorcos** [comment]
here's my solution that i figured out. seems messy though

```py
def optional(parser):
    @p.generate
    def _optional():
        r = yield p.times(parser, 0, 1)
        if len(r) > 0:
            result(r[0])
        else:
            result(None)
    return _optional
```

**Comment by sighingnow** [comment]
We can create a dummy parser which consumes nothing and returns `None`, then use the `try_choice` combinator:

~~~python
import parsec as p

def optional(parser):
    @p.generate
    def dummy():
        '''Return None without doing anything.'''
        yield p.string('')
        return None
    return parser ^ dummy    ## (^) means try_choice

s = p.string('xx')

print(optional(s).parse('xx')) // xx
print(optional(s).parse('xy')) // None
~~~

Thanks for your proposal @ccorcos  and I will add the `optional` combinator into the library later (maybe with better implementation).

**Comment by sighingnow** [comment]
If you have better solution, feel free to comment here.

**Comment by ccorcos** [comment]
That looks fine to me. I'm not terribly familiar with how the internals work but this looks fine.

**Comment by sighingnow** [comment]
Close as fixed.
