### ISSUE TITLE
Parser forward declaration

### ISSUE THREAD

**Issue by maximkulkin** [sighingnow/parsec.py#17]
In some cases you need have two parsers each of which need to reference the other one. E.g.

```python
number = regex('\d+')
# On next line Python will complain because "value" is not defined
list_value = string('[') >> many(value, string(',')) << string(']')
value = number | list_value
```

It would be nice to have a deferred (or forward) declaration for parsers. E.g.:

```python
@forward
def value():
    return number | list_value
number = regex('\d+')
list_value = string('[') >> many(value, string(',')) << string(']')
```

Implementation is trivial:
```python
def forward(f):
    @wraps(f)
    @Parser
    def forwarded(text, index):
        return f()(text, index)
    return forwarded
```
For bonus points, result can be cached to avoid calculating forwarded parser every time.

**Comment by sighingnow** [comment]
I think the `@generate` is all your need for this kind of parser. Your parser can be defined as:

~~~python
@generate
def value():
    ns = yield number | list_value
    return ns

number = regex('\d+')
list_value = string('[') >> sepBy(value, string(',')) << string(']')
~~~

Run it on test cases:

~~~python
>>> value.parse('1234')
1234

>>> value.parse('[123,456,789]')
['123', '456', '789']
~~~

And please notice that the `many` combinator means repeat a parser many times, here you need `sepBy` to represent numbers are separated by commas.

**Comment by maximkulkin** [comment]
Except for generate() does not work in Python 2.x and you have to use some ugly hacks to fix it.
