### ISSUE TITLE
Stateful parser

### ISSUE THREAD

**Issue by kenoph** [sighingnow/parsec.py#20]
Let's say I would like to implement something like python-style indentation-based nesting.
I would need to keep track of the current indentation level. Is there a simple way to do it in parsec.py?

**Comment by sighingnow** [comment]
I think add an class attribute to `Parser` and corresponding `getter/setter/mapper` would be enough for your problem.

I will push a patch for this feature (as well as examples) later.

**Comment by kenoph** [comment]
Thanks for the answer. For the time being, I'm doing like:

```python
def parse_block(indent):
    @generate
    def pb():
        whatever(indent)
    return pb
```
Btw, thank you very much for the project. I like Parsec and being able to do something similar in python is pretty cool.
