### ISSUE TITLE
Separated restricts ability to have no upper bound

### ISSUE THREAD

**Issue by foolswood** [sighingnow/parsec.py#27]
https://github.com/sighingnow/parsec.py/blob/d440082e38b7297b8c3de0cea4481cd059e11758/src/parsec/__init__.py#L450

If the upper bound is set to `None`, rather than having no upper bound this instead forces the lower bound number of repeats. Intentional?

**Comment by sighingnow** [comment]
I think this is by-design, but I cannot remember the reason. You can use `times(mint, float('inf'))` if you want a parser that repeats at least `mint` times.
