### ISSUE TITLE
optional consumes on failure

### ISSUE THREAD

**Issue by connerjohnston631** [sighingnow/parsec.py#29]
optional parser consumes input on failure, I am not sure if this is intended. For example, if I would like to parse an optional keyword "auto" followed by an identifier. If the keyword is not present, and the optional keyword parser can consume some of the identifier, then the optional parser will return the default value, and the identifier parser will return the remaining identifier.

lexeme1 = lambda p: p.skip(many1(space()))
lexeme = lambda p: p.skip(spaces())

def optional_auto_keyword():
  """returns string 'auto' or None """
  return optional(lexeme1(string('auto')))

def identifier():
  """returns string of identifier"""
  return lexeme(letter().joint(letter() | digit() | one_of('_'))).parsecmap(lambda x: x[0] + ''.join(x[1]))

example_0 = "abc;"
example_1 = "auto abc;"
example_2 = "other_identifier;"

def statement():
  """parses simple statement of optional 'auto' followed by identifier and terminated with semicolon"""
  return optional_auto_keyword().joint(identifier()).skip(one_of(';'))

#Expected: (None, 'abc') Actual: (None, 'bc') <-- optional_auto_keyword() consumed "a"
statement().parse(example_0)

#Expected: ('auto', 'abc') Actual: (same)
statement().parse(example_1)

#Expected: (None, 'other_identifier') Actual: (same)
statement().parse(example_2)

If this is unintended, I find that the following fix seems to work; returning the original index instead of res.index when returning the default value

def optional(p, default_value=None):
    '''`Make a parser as optional. If success, return the result, otherwise return
    default_value silently, without raising any exception. If default_value is not
    provided None is returned instead.
    '''
    @Parser
    def optional_parser(text, index):
        res = p(text, index)
        if res.status:
            return Value.success(res.index, res.value)
        else:
            # Return the maybe existing default value without doing anything.
            #FIX here: use index instead of res.index
            return Value.success(index, default_value)
    return optional_parser

**Comment by sighingnow** [comment]
Closed as we already have the `optional` parser combinator.
