### ISSUE TITLE
Tests are missing from Pypi pakage

### ISSUE THREAD

**Issue by grwlf** [sighingnow/parsec.py#32]
Hi. Debatable, but could you please include tests into the Pypi package? Python is the kind of language where we usually want to double-check the library after deployment.

**Comment by sighingnow** [comment]
> Hi. Debatable, but could you please include tests into the Pypi package? Python is the kind of language where we usually want to double-check the library after deployment.

Fixed. There's also [a new verison on pypi](https://pypi.org/project/parsec/3.6/). Thanks for your interest on this project.
