### ISSUE TITLE
`separated(end=False)` consumes trailing separator

### ISSUE THREAD

**Issue by andsens** [sighingnow/parsec.py#35]
`None` and `False` have no semantic difference in `separated`, they both allow a trailing separator.
https://github.com/sighingnow/parsec.py/blob/e74552e8fc067896a502763b77bc2f50895c1ae4/src/parsec/__init__.py#L498

There's two ways to fix the `end = False` case. [1] Fail if a trailing separator is detected, or [2] do not consume the trailing separator.  
The docs for `separated()` say
> When `end` is False, a trailing separator is not allowed.

Which would mean [1].  
However, the way `sepBy` is documented
> `sepBy(p, sep)` parses zero or more occurrences of p, separated by `sep`.

I would actually expect parsing to just stop and return the data parsed so far. It would also be more powerful that way in the way you can combine it with other parsers afterwards.

**Comment by sighingnow** [comment]
FYI: hi @andsens I have just uploaded a new release to pypi: https://pypi.org/project/parsec/3.8/
