### ISSUE TITLE
Support recursive parsing using fixed-point trick

### ISSUE THREAD

**Issue by sighingnow** [sighingnow/parsec.py#39]
Raised by https://stackoverflow.com/questions/67841197/parsing-text-with-pythons-parsec-py-library/67880757#67880757

I think fixed-point combinator (Y combinator) is the way for that.

**Comment by drewolson** [comment]
I think this effectively works now:

```python
from parsec import Parser, string, any

fix = lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))

@Parser
@fix
def expr(recur):
    return (string("(") >> recur << string(")")) | any()

result = expr.parse("((x))")

print(result)
```
```
$ python example.py 
x
```

**Comment by sighingnow** [comment]
> I think this effectively works now:
> 
> ```python
> from parsec import Parser, string, any
> 
> fix = lambda f: (lambda x: x(x))(lambda y: f(lambda *args: y(y)(*args)))
> 
> @Parser
> @fix
> def expr(recur):
>     return (string("(") >> recur << string(")")) | any()
> 
> result = expr.parse("((x))")
> 
> print(result)
> ```
> 
> ```
> $ python example.py 
> x
> ```

I missed the message! Thanks for your try and I will added this method to the repo.
