### ISSUE TITLE
feature request: type hints

### ISSUE THREAD

**Issue by lmmarsano** [sighingnow/parsec.py#41]
Could the distribution [include type hints for static type checking](https://www.python.org/dev/peps/pep-0561/)?
To support this, parsec could use inline type hints, or (to support python 2) put them in stub files.
For my own purposes, I've already written [3rd party stubs](https://github.com/lmmarsano/parsec-stubs).

While preparing the stubs, I've noticed that with little change parsec could accept sequences of any kind instead of just text.
Would that be worth trying?

**Comment by sighingnow** [comment]
> For my own purposes, I've already written 3rd party stubs.

Thanks for doing that! Could you submit a pull request to add the `.pyi` file into this repo? I could cut a new release then.

> I've noticed that with little change parsec could accept sequences of any kind instead of just text.

The parser works on a sequence that supports methods like indexing and slices. I think '[char]' would work as well. For other kinds of sequences, the parsers only work on `str` (e.g., `regex`) may fail, but the parser itself should still work well.
