### ISSUE TITLE
Prevent infinite loop in many() by checking if input has been consumed

### ISSUE THREAD

**Issue by andsens** [sighingnow/parsec.py#43]
Consider this code:
```
some_text= many(string('a'))
atom = string('atom')
ast = many(atom | some_text)
```

This will loop infinitely because `many()` always returns success even if it hasn't consumed anything (as it should). That behavior however directly causes parsers like `many(many(...))` to loop infinitely because the underlying`times()` continues until a parser fails.  
It's fixable directly in the parser by changing `some_text` to `many1(string('a'))` of course, but that might hurt reusability and is quite confusing for beginners and can be a problem that is hard to track down for advanced users.  
The reason I'm not just sending a pull request is because I'm not quite sure if my idea for a solution is good enough. It relies on the internals of how `many()` works. My suggested fix:
Change this: https://github.com/sighingnow/parsec.py/blob/a58b6e89fa4f557edef97e6dfffd8f1256312754/src/parsec/__init__.py#L418-L425

To this:
```py
def times_parser(text, index):
    cnt, values, res = 0, Value.success(index, []), None
    while cnt < maxt:
        res = p(text, index)
        if res.status:
            if maxt == float('inf') and res.index == index: # <---
              break
            values = values.aggregate(
                Value.success(res.index, [res.value]))
            index, cnt = res.index, cnt + 1
```

As far as I can see the change only affects the parser if it would loop infinitely. We can deterministically predict that the next loop is going to do the exact same thing.
Alternatively you could do it directly in `many()`:
```py
def many(p):
    '''Repeat a parser 0 to infinity times. DO AS MUCH MATCH AS IT CAN.
    Return a list of values.'''

    @Parser
    def many_parser(text, index):
        values, res = Value.success(index, []), None
        while index < len(text):
            res = p(text, index)
            if not res.status or res.index == index:
                break
            values = values.aggregate(
                Value.success(res.index, [res.value]))
            index = res.index
        return values
    return many_parser
```

I think the second option is quite a bit cleaner, even though it's a little bit more code.

**Comment by sighingnow** [comment]
The fix looks feasible to me. Thanks!

I think when `res.index == index` we do need to break the loop.

**Comment by sighingnow** [comment]
Thank you @andsens , the patch has been pushed to main.
