### ISSUE TITLE
query on `separated` operation

### ISSUE THREAD

**Issue by mentaal** [sighingnow/parsec.py#47]
Hi there, 
I have a query on the operation of the `separated` function please.

I'm not sure if this could be regarded as a bug or normal operation. Below is an example script showing how greediness in the choice combinator affects operation of the combinators derived from `separated` such as sepBy in this case.

```python
from parsec import *

whitespace = regex(r'\s*', re.MULTILINE)
lexeme = lambda p: p << whitespace

number = lexeme(regex(r'\d+').parsecmap(int))


less_than               = lexeme(string('<'))
less_than_or_equal      = lexeme(string('<='))
greater_than            = lexeme(string('>'))
greater_than_or_equal   = lexeme(string('>='))

relational_ops = (less_than ^ less_than_or_equal ^ greater_than ^ greater_than_or_equal).desc('relational operators')
#relational_ops = (less_than_or_equal ^ greater_than_or_equal ^ less_than ^ greater_than).desc('relational operators')

relational_parser = number + sepBy(relational_ops + number, whitespace)

print("Works as expected: ", relational_parser.parse('2 < 4 > 3'))
print("Works as expected: ", relational_parser.parse('2 > 4 > 3'))
print("Doesn't work!:", relational_parser.parse(f'2 <= 4 > 3'))
print("Doesn't work!:", relational_parser.parse('2 >= 4'))

```

Basically, the order of the relational parses in `relational_ops` affects the results obtained with `relational_parser`.

For example, when parsing a string with `>=`, the parser matches `>`, doesn't mind any further matches beginning with '=' so stops. 
I had thought that combining the parsers with backtracking (`^`) would have resolved this.

The behavior of the parser works as expected if you use the definition of `relational_ops` commented below the original definition. The difference being that the two character parsers are tried first. 

Would this be considered a bug? If not, what is the canonical way to describe the desired behavior? I'd like to keep the order of operators as originally defined because the dsl I am parsing has them in this order and I suspect changing the order will affect correctness of the parser.

I guess one option would be to define, for example `less_than` to match `<` only if the next character is not an `=`.
Incidentally, is there a provided combinator for expressing negation such as for the case just described? I'm sure I can write my own but it seems like a generally useful combinator to have.

Thanks,
Greg

**Comment by mentaal** [comment]
As a workaround, this would work for example:

```python
def lookahead_fail(p: Parser):
    '''Parses without consuming and fails if successful (useful for implementing
       negation
    '''
    @Parser
    def lookahead_parser(text, index):
        res = p(text, index)
        if res.status:
            return Value.failure(index, "shouldn't come next")
        else:
            return Value.success(index, res.expected)
    return lookahead_parser


less_than               = lexeme(string('<')) << lookahead_fail(string('='))
less_than_or_equal      = lexeme(string('<='))
greater_than            = lexeme(string('>')) << lookahead_fail(string('='))
greater_than_or_equal   = lexeme(string('>='))


```

**Comment by sighingnow** [comment]
Hi @mentaal,

Thanks for your attention on this repo and examples in #44 and #46. I will back there next week and will go through these issues and pull requests carefully.

**Comment by sighingnow** [comment]
> Would this be considered a bug?

It is by design. Parsers connected by `|` will be executed as the defined order and will stop once one of them succeeds. Currently the operator `|` doesn't have "match as long as possible" semantics.

> As a workaround, this would work for example:

I think we could add the `lookahead_fail` operator into the library, and I think `unless` would be a better name, e.g.,

```python
unless(string('<'), string('='))
```

And I think we could use the `\` operator for it.

**Comment by sighingnow** [comment]
> > Would this be considered a bug?
> 
> It is by design. Parsers connected by `|` will be executed as the defined order and will stop once one of them succeeds. Currently the operator `|` doesn't have "match as long as possible" semantics.
> 
> > As a workaround, this would work for example:
> 
> I think we could add the `lookahead_fail` operator into the library, and I think `excepts` would be a better name, e.g.,
> 
> ```python
> excepts(string('<'), string('='))
> ```
> 
> And I think we could use the `\` operator for it.
> 
> Edit: rename `unless` to `excepts`.

Implemented on main.

**Comment by mentaal** [comment]
Great, thank you for the clarifications and the feature addition!
