### ISSUE TITLE
`separated` does not consume the last `sep`, even if `end=True`

### ISSUE THREAD

**Issue by worldmaker18349276** [sighingnow/parsec.py#48]
```python
>>> separated(string("a"), string(","), 3, 3, end=False).parse_partial("a,a,a,")
(['a', 'a', 'a'], ',')
>>> separated(string("a"), string(","), 3, 3, end=None).parse_partial("a,a,a,")
(['a', 'a', 'a'], ',')
>>> separated(string("a"), string(","), 3, 3, end=True).parse_partial("a,a,a,")
(['a', 'a', 'a'], ',')
```

**Comment by sighingnow** [comment]
It should be a bug.

**Comment by sighingnow** [comment]
Fixed in main.

**Comment by ermakov-oleg** [comment]
It seems that in the last release they broke the following behavior:
```
>>> separated(string("a"), string(","), 0, 300, end=False).parse_partial("a,a,a,")
(['a', 'a', 'a'], '')
```

When maxt is greater than the number of items, the last comma will also be consumed.
Is this expected behavior?

**Comment by sighingnow** [comment]
> It seems that in the last release they broke the following behavior:
> 
> ```
> >>> separated(string("a"), string(","), 0, maxt=float('inf'), end=False).parse_partial("a,a,a,")
> (['a', 'a', 'a'], '')
> ```
> 
> When maxt is greater than the number of items, the last comma will also be consumed. Is this expected behavior?

Sorry I missed this message and I was thinking the issue has been fixed. Thanks for raising this up.

**Comment by sighingnow** [comment]
Close as fixed.
