### ISSUE TITLE
Pip install of version 3.0 does not reflect latest code

### ISSUE THREAD

**Issue by umeat** [sighingnow/parsec.py#5]
I am installing parsec as a requirement of another module (using setup.py), like so:

`install_requires=['parsec==3.0'],`
`dependency_links=['http://github.com/sighingnow/parsec.py/tarball/master#egg=parsec-3.0']`

However, the code installed is not the most recent. Specifically, the **joint** function is defined as:

`def joint(pa, pb):
    '''Joint two parsers, implements the operator of "(+)".'''
    return pa.joint(pb)`

Perhaps this could be fixed by changing the version in your setup.py to 3.1 (maybe that should be done regardless?). Then I can reference 3.1, instead of 3.0.

**Comment by sighingnow** [comment]
Sorry for my late reply. I have uploaded the latest code to pypi and bump version to 3.1.
