### ISSUE TITLE
Syntax error reported, using example code.

### ISSUE THREAD

**Issue by capn-freako** [sighingnow/parsec.py#9]
When using your example code, I'm getting the following error:

SyntaxError: 'return' with argument inside generator

**Comment by sighingnow** [comment]
This syntax is Python 3 only, please use Python 3 instead. For Python 2, an example about how to use generator can be found in `ParserGeneratorTest` in file tests/test_parsec.py.

**Comment by capn-freako** [comment]
Thanks.

Can you tell me how to return a value from a generator parser, when using Python 2?

**Comment by capn-freako** [comment]
This code seems to work, under Python 2:

```
@generate('AMI node')
def node():
    'Parse AMI node.'
    yield lparen
    label = yield symbol
    values = yield many1(expr)
    yield rparen
    err = StopIteration()
    err.value = (label, values)
    raise err

```

**Comment by sighingnow** [comment]
I'm afraid use exceptions to pass return value is not a good practice, although, it does work with Python 2. I will mention this issue in the documentation so that other guys with the same trouble could reach it easily. 

Thanks very much for your suggestions.
